name: stands3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: '>=2.8.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  video_player: ^2.1.15
  audioplayers: ^0.20.1
  gradient_app_bar: ^0.1.3
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.3
  google_mobile_ads: ^1.1.0
  
  material_design_icons_flutter: ^5.0.6595
  new_gradient_app_bar: ^0.2.0
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2

dependency_overrides:
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  
  
    - assets/images/sound_board_images/

    - assets/icon/app background.jpg
    - assets/jojo_text-removebg-preview.png
    - assets/menacing-removebg-preview.png




    #
    #
    - assets/images/image1.jpg
    - assets/images/image2.jfif
    - assets/images/image3.png
    - assets/images/image4.png
    - assets/images/image5.jpg
    - assets/images/image6.jpeg
    - assets/images/image7.jpg
    - assets/images/image8.jpg
    - assets/images/image9.jpg
    - assets/images/image10.jpg
    - assets/images/image11.jpg
    - assets/images/jotaro.jpg

    - assets/images/stat wheel new.png

    #
    #
    #
    - assets/images/background scroll.jfif
    - assets/images/soundboard background.png
    - assets/images/dio background.jpg
    - assets/images/jotaro background.jfif
    - assets/images/backgrounds/space background.jpg
    - assets/images/backgrounds/forest background.jpg
    - assets/images/backgrounds/fire background.jpg
    - assets/images/backgrounds/old west.jpg
    - assets/images/backgrounds/france background.jpg
    - assets/images/backgrounds/cast background.jpg
    - assets/images/backgrounds/joseph background.jpg
    - assets/images/backgrounds/western background.jpg
    - assets/images/backgrounds/western background 2.jpg
    - assets/images/backgrounds/western background 3.jpg
    - assets/images/backgrounds/sand background.jpg
    - assets/images/backgrounds/the world background.jpg
    - assets/images/backgrounds/plane background.jpg
    - assets/images/backgrounds/under water background.jpg
  #
  #
  #
    - assets/images/stands/star_platinum-removebg.png
    - assets/images/stands/H-green-removebg.png
    - assets/images/stands/magicians_red-removebg.png
    - assets/images/stat_wheel-removebg.png
    - assets/images/stands/hermit_purple3-removebg.png
    - assets/images/stands/silver_chariot-removebg.png
    - assets/images/stands/silver_chariot_2-removebg.png
    - assets/images/stands/the_fool-removebg-preview.png
    - assets/images/stands/the_world-removebg-preview.png
    - assets/images/stands/the_world_2-removebg-preview.png
    - assets/images/stands/tower_of_gray-removebg-preview.png
    - assets/images/stands/dark_blue_moon_2-removebg-preview.png
    - assets/images/stands/strength-removebg-preview.png
    - assets/images/stands/strength.png

    #
    #
    #
    - assets/images/stands/stand heads/star platinum head.jpg
    - assets/images/stands/stand heads/h-green head.jpg
    - assets/images/stands/stand heads/magicians red head.gif
    - assets/images/stands/stand heads/hermit purple head.png
    - assets/images/stands/stand heads/silver chariot head.png
    - assets/images/stands/stand heads/the fool head.png
    - assets/images/stands/stand heads/the world head.png
    - assets/images/stands/stand heads/tower of gray head.png
    - assets/images/stands/stand heads/strength head.png
    - assets/images/stands/stand heads/dark blue moon head.png
    - assets/jojo1-3_Trim_Trim.mp4
    #
    #
    #
    - assets/sounds/wow1.mp3
    - assets/sounds/wow2.mp3
    - assets/sounds/wow3.mp3
    - assets/sounds/wow4.mp3
    - assets/sounds/wow5.mp3
    - assets/sounds/wow6.mp3
    - assets/sounds/wow7.mp3
    - assets/sounds/wow8.mp3
    - assets/sounds/wow9.mp3
    - assets/sounds/wow10.mp3
    - assets/sounds/wow11.mp3
    - assets/sounds/wow12.mp3
    - assets/sounds/wow13.mp3
    - assets/sounds/wow14.mp3
    - assets/sounds/wow15.mp3
    - assets/sounds/wow16.mp3
    - assets/sounds/wow17.mp3
    - assets/sounds/wow18.mp3
    - assets/sounds/wow19.mp3
    - assets/sounds/wow20.mp3
    - assets/sounds/wow21.mp3
    - assets/sounds/wow22.mp3
    - assets/sounds/wow23.mp3
    - assets/sounds/wow24.mp3
    - assets/sounds/wow25.mp3
    - assets/sounds/wow26.mp3
    - assets/sounds/wow27.mp3
    - assets/sounds/wow28.mp3
    - assets/sounds/wow29.mp3
    - assets/sounds/wow30.mp3
    - assets/sounds/wow31.mp3
    - assets/sounds/wow32.mp3
    - assets/sounds/wow33.mp3
    - assets/sounds/wow34.mp3
    - assets/sounds/wow35.mp3
    - assets/sounds/wow36.mp3
    - assets/sounds/wow37.mp3
    - assets/sounds/wow38.mp3
    - assets/sounds/wow39.mp3
    - assets/sounds/wow40.mp3
    - assets/sounds/wow41.mp3
    - assets/sounds/wow42.mp3
    - assets/sounds/oh shit.mp3
    - assets/sounds/son of a bitch.mp3
    - assets/sounds/silver chariot.mp3
    - assets/sounds/bravo bravo.mp3
    - assets/sounds/igg.mp3
    - assets/sounds/mosquito.mp3
    - assets/sounds/water droplit.mp3
    - assets/sounds/ship horn.mp3
  




  
    - assets/images/stat wheels/h-green stat.png
    - assets/images/stat wheels/magicians red stat.png
    - assets/images/stat wheels/silver chariot stat.png
    - assets/images/stat wheels/hermit purple stat.png
    - assets/images/stat wheels/the fool stat.png
    - assets/images/stat wheels/the world stat.png
    - assets/images/stat wheels/tower of gray stat.png
    - assets/images/stat wheels/dark blue moon stat.png
    - assets/images/stat wheels/strength stat.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
